const ACTION_TYPES = {
  // CREATE_TASK: 'CREATE_TASK',
  // UPDATE_TASK: 'UPDATE_TASK',
  // DELETE_TASK: 'DELETE_TASK',

  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
};

export default ACTION_TYPES;
